apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-crds
  namespace: linkerd
spec:
  chart:
    spec:
      chart: linkerd-crds
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: linkerd
      version: 2026.1.1
  interval: 1h
  timeout: 5m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd
  namespace: linkerd
spec:
  chart:
    spec:
      chart: linkerd-control-plane
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: linkerd
      version: 2026.1.1
  interval: 1h
  timeout: 10m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
    - name: linkerd-crds
      namespace: linkerd
  install:
    crds: Skip
    remediation:
      retries: 5
  upgrade:
    crds: Skip
    remediation:
      retries: 5
  valuesFrom:
    - kind: Secret
      name: linkerd-trust-anchor
      valuesKey: ca.crt
      targetPath: identityTrustAnchorsPEM
  values:
    identity:
      issuer:
        scheme: kubernetes.io/tls
    disableHeartBeat: true
    proxy:
      defaultInboundPolicy: all-unauthenticated
