apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: 1.19.1
  releaseName: cert-manager
  targetNamespace: cert-manager
  interval: 1h
  timeout: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace