apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: allow-linkerd-capabilities
  namespace: kyverno
spec:
  exceptions:
  - policyName: disallow-capabilities
    ruleNames:
    - adding-capabilities
  match:
    any:
    - resources:
        kinds:
        - Pod
        - Deployment
        annotations:
          linkerd.io/inject: enabled
    - resources:
        kinds:
        - Pod
        - Deployment
        namespaceSelector:
          matchLabels:
            linkerd.io/inject: enabled
    - resources:
        kinds:
        - Pod
        - Deployment
        namespaces:
          - linkerd
  podSecurity:
    - controlName: Capabilities
      images:
        - '*/linkerd/proxy*'
      restrictedField: spec.initContainers[*].securityContext.capabilities.add
      values:
        - NET_ADMIN
        - NET_RAW