apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: allow-linkerd-capabilities
  namespace: kyverno
spec:
  match:
    any:
    - resources:
        kinds:
        - Pod
        - Deployment
        - ReplicaSet
        annotations:
          linkerd.io/inject: enabled
    - resources:
        kinds:
        - Pod
        - Deployment
        - ReplicaSet
        namespaceSelector:
          matchLabels:
            linkerd.io/inject: enabled
    - resources:
        kinds:
        - Pod
        - Deployment
        - ReplicaSet
        namespaces:
          - linkerd
  
  podSecurity:
    - controlName: Capabilities
      images:
        - '*/linkerd/proxy*'
      restrictedField: spec.initContainers[*].securityContext.capabilities.add
      values:
        - NET_ADMIN
        - NET_RAW
    - controlName: Capabilities
      images:
        - '*/linkerd/proxy*'
      restrictedField: spec.containers[*].securityContext.capabilities.add
      values:
        - NET_ADMIN
        - NET_RAW