apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: allow-linkerd-capabilities-traefik
  namespace: traefik-system
spec:
  policyRefs:
  - kind: ValidatingPolicy
    name: disallow-capabilities
  matchConditions:
    - name: namespace-has-linkerd-inject
      expression: >-
        
    - name: only-except-linkerd-proxy-capabilities
      expression: >-
         ((object.metadata.?annotations['linkerd.io/inject'].orValue('') == 'enabled') || (resource.Get("v1", "namespaces", "", request.namespace).metadata.?annotations['linkerd.io/inject'].orValue('') == 'enabled') || (request.namespace == 'linkerd')) && (has(object.spec.template) ? (object.spec.template.spec.containers + object.spec.template.spec.?initContainers.orValue([])) : (object.spec.containers + object.spec.?initContainers.orValue([]))).all(c, !c.?securityContext.?capabilities.?add.orValue([]).exists(cap, cap in ['NET_ADMIN', 'NET_RAW']) || c.image.matches('^.*linkerd/proxy.*$'))
---
apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: allow-linkerd-capabilities-linekrd
  namespace: linkerd
spec:
  policyRefs:
  - kind: ValidatingPolicy
    name: disallow-capabilities
  matchConditions:
    - name: check-linkerd-injection
      expression: >-
        ((object.metadata.?annotations['linkerd.io/inject'].orValue('') == 'enabled') || (object.metadata.?labels['linkerd.io/inject'].orValue('') == 'enabled') || (request.namespace == 'linkerd'))
    - name: only-except-linkerd-proxy-capabilities
      expression: >-
         (has(object.spec.template) ? (object.spec.template.spec.containers + object.spec.template.spec.?initContainers.orValue([])) : (object.spec.containers + object.spec.?initContainers.orValue([]))).all(c, !c.?securityContext.?capabilities.?add.orValue([]).exists(cap, cap in ['NET_ADMIN', 'NET_RAW']) || c.image.matches('^.*linkerd/proxy.*$'))
---
apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: allow-linkerd-capabilities-kyverno
  namespace: kyverno
spec:
  policyRefs:
  - kind: ValidatingPolicy
    name: disallow-capabilities
  matchConditions:
    - name: only-except-linkerd-proxy-capabilities
      expression: >-
         ((object.metadata.?annotations['linkerd.io/inject'].orValue('') == 'enabled') || (object.metadata.?labels['linkerd.io/inject'].orValue('') == 'enabled') || (request.namespace == 'linkerd')) && (has(object.spec.template) ? (object.spec.template.spec.containers + object.spec.template.spec.?initContainers.orValue([])) : (object.spec.containers + object.spec.?initContainers.orValue([]))).all(c, !c.?securityContext.?capabilities.?add.orValue([]).exists(cap, cap in ['NET_ADMIN', 'NET_RAW']) || c.image.matches('^.*linkerd/proxy.*$'))
---
apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: allow-linkerd-capabilities-limited
  namespace: limited-services
spec:
  policyRefs:
  - kind: ValidatingPolicy
    name: disallow-capabilities
  matchConditions:
    - name: only-except-linkerd-proxy-capabilities
      expression: >-
         ((object.metadata.?annotations['linkerd.io/inject'].orValue('') == 'enabled') || (object.metadata.?labels['linkerd.io/inject'].orValue('') == 'enabled')) && (has(object.spec.template) ? (object.spec.template.spec.containers + object.spec.template.spec.?initContainers.orValue([])) : (object.spec.containers + object.spec.?initContainers.orValue([]))).all(c, !c.?securityContext.?capabilities.?add.orValue([]).exists(cap, cap in ['NET_ADMIN', 'NET_RAW']) || c.image.matches('^.*linkerd/proxy.*$'))
