apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: gateway-helm
  releaseName: eg
  dependsOn:
    - name: linkerd
      namespace: linkerd
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  targetNamespace: envoy-gateway-system
  values:
    crds:
      gatewayAPI:
        enabled: false
      envoyGateway:
        enabled: true
    config:
      envoyGateway:
        extensionApis:
          enableBackend: true