apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gloo-platform
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://storage.googleapis.com/solo-public-helm
