apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./gloo
  - ./collector
  # - ./traefik
  - ./envoy-gateway
  - ./grafana-charts
  - ./minio
  - ./mimir
  - ./loki
  - ./tempo