apiVersion: policies.kyverno.io/v1
kind: GeneratingPolicy
metadata:
  name: gen-linkerd-rules
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["namespaces"]
    objectSelector:
      matchLabels:
        linkerd.io/injection: enabled
  variables:
    - name: targetNs
      expression: "object.metadata.name"
    - name: resources
      expression: |
        [
          {
            "apiVersion": dyn("policy.linkerd.io/v1beta3"),
            "kind": dyn("Server"),
            "metadata": dyn({
              "name": "default-http"
            }),
            "spec": dyn({
              "podSelector": dyn({
                "matchLabels": dyn({})
              }),
              "port": dyn("http")
            })
          },
          {
            "apiVersion": dyn("policy.linkerd.io/v1beta3"),
            "kind": dyn("HTTPRoute"),
            "metadata": dyn({
              "name": "health-metrics"
            }),
            "spec": dyn({
              "parentRefs": dyn([
                {
                  "name": "default-http",
                  "kind": "Server",
                  "group": "policy.linkerd.io"
                }
              ]),
              "rules": dyn([
                {
                  "matches": [
                    {
                      "path": {
                        "type": "PathPrefix",
                        "value": "/health"
                      }
                    },
                    {
                      "path": {
                        "type": "PathPrefix",
                        "value": "/metrics"
                      }
                    }
                  ]
                }
              ])
            })
          },
          {
            "apiVersion": dyn("policy.linkerd.io/v1alpha1"),
            "kind": dyn("AuthorizationPolicy"),
            "metadata": dyn({
              "name": "allow-kubelet-probes"
            }),
            "spec": dyn({
              "targetRef": dyn({
                "group": "policy.linkerd.io",
                "kind": "HTTPRoute",
                "name": "health-metrics"
              }),
              "requiredAuthenticationRefs": dyn([])
            })
          }
        ]
  generate:
    - expression: "generator.Apply(variables.targetNs, variables.resources)"
