apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno-policies
  namespace: kyverno
spec:
  chart:
    spec:
      chart: kyverno-policies
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno
      version: 3.7.0
  interval: 1h
  timeout: 5m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    podSecurityStandard: baseline
    podSecuritySeverity: medium
    validationFailureAction: Enforce
    background: true
