apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: otel-operator
  namespace: flux-system
spec:
  type: oci
  interval: 1h
  url: oci://ghcr.io/open-telemetry/opentelemetry-helm-charts