apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik-namespace.yaml
  - envoy-namespace.yaml
  - linkerd-namespace.yaml
  - monitoring-namespace.yaml
  - otel-col-namespace.yaml
  - except-linkerd-proxy.yaml
  - except-hostpath-otel-logs.yaml
  - restrict-envoy-backends.yaml
