apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kro
  namespace: kro
spec:
  interval: 60m
  chartRef:
    kind: OCIRepository
    name: kro
    namespace: kro
  releaseName: kro
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace