apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kro
  namespace: kro
spec:
  interval: 60m
  chart:
    spec:
      chart: kro
      version: 0.4.1
      sourceRef:
        kind: OCIRepository
        name: kro
        namespace: kro
  releaseName: kro
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace